FROM python:3.11-slim
WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc libpq-dev \
    && rm -rf /var/lib/apt/lists/*


COPY api/pyproject.toml api/alembic.ini ./
COPY api/src ./src                   
COPY api/migrations ./migrations
COPY api/wsgi.py ./wsgi.py


RUN pip install --upgrade pip setuptools wheel \
    && pip install . 

ENV FLASK_APP=wsgi:app
EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
