services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: masterquest
      POSTGRES_PASSWORD: masterquest
      POSTGRES_DB: masterquest
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.api
    restart: always
    environment:
      FLASK_ENV: development
      FLASK_APP: app:create_app
      FLASK_DEBUG: 1
      DATABASE_URL: postgresql+psycopg2://masterquest:masterquest@db:5432/masterquest
      SECRET_KEY: "dev-secret"
    depends_on:
      - db
    volumes:
      - ../api:/app
    working_dir: /app
    ports:
      - "5000:5000"
    command: flask run --debug --host=0.0.0.0 --port=5000

volumes:
  db-data:
